### ISSUE TITLE
Unknown Filter Mode

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#180]
Getting these messages in rapid fire when I launch the app without music being cued up.
unknown filter mode - do we update the alphawheel or what?
unknown filter mode - do we draw the alphawheel or what?

**Comment by flight404** [comment]
I think this is addressed by adding a check for playState == stopped. Seems if the Player state is stopped (and not paused), it slips through all the checks and ends up triggering the unknown filter mode comments.

 // show the wheel if we're paused...
if ( mIpodPlayer.getPlayState() == ipod::Player::StatePaused || mIpodPlayer.getPlayState() == ipod::Player::StateStopped ) {

Close the issue if this seems right to you.

**Comment by RandomEtc** [comment]
That seems right. If we still get inconsistent startup states we could move to saying `if ( mIpodPlayer.hasPlayingTrack() && mIpodPlayer.getPlayState() != ipod::Player::StateStopped )` at the beginning of that section. This might put us in a weird spot where pressing play zooms to a track but no current track is displayed in the interface, so I think your way is better (stop really is just like paused if there's a track queued up).

I am still tripped up by these overlapping states. The ipod player can be playing or paused or stopped, and have a playing track or not. You can be stopped but still have a playing track, it seems, which was news to me!
